bot:
  token: ${BOT_TOKEN}
  api_url: ${BOT_API_URL}
  secret: ${BOT_SECRET}

postgres:
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  db: ${POSTGRES_DB}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}