bot:
  token: ${BOT_TOKEN}
  api_url: ${BOT_API_URL}
  secret: ${BOT_SECRET}

storage:
  type: ${STORAGE_TYPE} # "fs" or "postgres" (default: postgres)
  path: ${STORAGE_PATH} # path to JSON file, only for "fs" (default: data.json)

postgres:
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  db: ${POSTGRES_DB}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}